In [ ]:
import numpy as np

# 1. 1차원 배열

In [ ]:
a = [1, 2, 3, 4, 5, 10, 20, "가", "나"]
print(a)
print(type(a))

[1, 2, 3, 4, 5, 10, 20, '가', '나']
<class 'list'>


In [ ]:
a = np.array([1, 2, 3, 4, 5, 10, 20, "가", "나"])
print(a)
print(type(a))  # ndarray(n-dimention)
print(a.shape)  # 형태
print(a.ndim)   # 차원
print(a.dtype)  # 데이터 타입 (<U11 : 유니코드, 11bite)

['1' '2' '3' '4' '5' '10' '20' '가' '나']
<class 'numpy.ndarray'>
(9,)
1
<U11


In [ ]:
a = np.array([1, 2, 3, 4, 5, 10, 20, "30", "40"], dtype=float)  # 형식 지정 가능
print(a)
print(a.dtype)

[ 1.  2.  3.  4.  5. 10. 20. 30. 40.]
float64


## 1) 벡터화 연산

- 벡터 = 일차원 배열
- 매트릭스 = 2차원 배열

In [ ]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(a*2)
# print(a-2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
b = np.array(a)
print(b*2)
print(b-2)
print(b/2)

[ 0  2  4  6  8 10 12 14 16 18]
[-2 -1  0  1  2  3  4  5  6  7]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


## 2) 인덱스 접근

In [ ]:
print(b[0], b[2])

0 2


# 2. 2차원 배열

In [ ]:
a = np.array([ [1, 2, 3], [4, 5, 6] ])
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


## 인덱스 접근

In [ ]:
print(a[0])
print(a[1])

print(a[0][0], a[1][1])
print(a[0, 0], a[1, 1])

print("------------------------------------------")

b = [ [1, 2, 3], [4, 5, 6] ]
print(b[0][0], b[1][1])
# print(b[0, 0], b[1, 1]) -> 리스트는 안됨

print("------------------------------------------")

print(len(a), len(a[0]))

[1 2 3]
[4 5 6]
1 5
1 5
------------------------------------------
1 5
------------------------------------------
2 3


# 3. 3차원 배열

In [ ]:
a = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],
              [[9, 10, 11, 12], [13, 14, 15, 16]]])

print(a)
print(a.shape)
print(a.ndim)

print("------------------------------------------")

print(len(a), len(a[0]), len(a[0][0]))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
(2, 2, 4)
3
------------------------------------------
2 2 4


In [ ]:
a = np.array([[[[1]]]])
print(a)
print(a.shape)
print(a.ndim)

[[[[1]]]]
(1, 1, 1, 1)
4


# 4. 집계 함수

In [ ]:
x = np.random.randn(8) # n -> 정규분포내에서 난수 출력
print(x)

y = np.random.randn(8)
print(y)

[-0.06670661 -0.27133693 -0.32734191 -0.31137209  0.05162072  0.9039403
 -0.12708812  1.8965892 ]
[-0.23695658 -1.80437411 -0.7182084   0.69285326 -1.36806274 -0.07557129
 -0.34039552 -0.57796626]


In [ ]:
np.maximum(x, y)  # x와 y중 큰 값 골라냄

array([-0.06670661, -0.27133693, -0.32734191,  0.69285326,  0.05162072,
        0.9039403 , -0.12708812,  1.8965892 ])

In [ ]:
arr = np.random.randn(5, 4)
print(arr)

[[ 1.63892684  0.04157319 -0.17326757 -0.26853511]
 [-1.14563068 -0.58050531  0.47318842  1.58836882]
 [-1.62133979  0.64369499  0.65420582 -0.84609467]
 [-2.65332917  2.14436053  0.87347981 -0.80610568]
 [ 1.19736284 -0.57230689  0.88553461 -1.16506421]]


In [ ]:
print(arr.sum())  # 전체 원소에 대한 함수
print(arr.sum(axis=0)) # 열의 합계
print(arr.sum(axis=1)) # 행의 합계

0.3085168060164001
[-2.58400995  1.67681651  2.71314109 -1.49743085]
[ 1.23869735  0.33542126 -1.16953365 -0.44159451  0.34552635]


# 5. 배열의 인덱싱

In [ ]:
arr= np.array([0, 1, 2, 3, 4])

print(arr[2], arr[3], arr[-1], arr[-3])

2 3 4 2


In [ ]:
arr = np.array([i for i in range(10)])
print(arr)

idx = np.array([True, False, True, False, True, False, True, False, True, False])

print(arr[idx])
print(arr[arr%2==0])
print(arr[arr%3==0])
print(arr[arr%4==1])

# arr에서 3으로 나누면 나눠지고 4로 나누면 1이 남는 수
print(arr[(arr%3==0) & (arr%4==1)])

(arr>10) & (arr<5)
(arr>10).any() and (arr<5).any()

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]
[0 3 6 9]
[1 5 9]
[9]


False

# 6. 슬라이싱

In [ ]:
arr = np.array([[0, 1, 2, 3],
                [4, 5, 6, 7],
                [8, 9, 10, 11]])

print(arr[0, 0:2])
print("----------------------------------")
print(arr[1:3, 0:2])
print("----------------------------------")
print(arr[0, :])
print("----------------------------------")
print(arr[[2, 1, 0], :])  # 행의 순서 지정 가능
print("----------------------------------")
print(arr[:, [1, 2]])     # 가져올 열 지정 가능

[0 1]
----------------------------------
[[4 5]
 [8 9]]
----------------------------------
[0 1 2 3]
----------------------------------
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
----------------------------------
[[ 1  2]
 [ 5  6]
 [ 9 10]]


# 7. numpy 자료형

- b : bool
- i : 정수형
- u(unsigned) : 부호없는 정수형(양수값 최대 활용)
- f : 실수형, 부동 소수점
- c : 복소수
- O : 객체
- S : 바이트 문자열(ASCII코드) -> 영어만 쓸 때 유리
- U : 유니코드 문자열 -> 다양한 언어 쓸 때 사용

In [ ]:
# arr = np.array([1, 2, 3], dtype="f")
arr = np.array([1, 2, 3], dtype=np.float16) # 정밀한 크기 지정 가능
print(arr.dtype)

float16


In [ ]:
arr = np.array([1, 2, 3], dtype="S")
print(arr.dtype)
print(arr[0]+arr[1]) # b'12'-> byte표시, 모든 문자열이 1byte로(ASCII코드)

|S1
b'12'


In [ ]:
arr = np.array([1, 2, 3], dtype="U")
print(arr.dtype)
print(arr[0]+arr[1])

<U1
12


# 8. 배열 생성

- np.array()
- np.zeros() : 0행렬
    - np.ones_like() : 0으로 채워진 행렬을 1로 채워줌
- np.ones() : 단위행렬
- np.empty() : 값을 채우지 않고 생성(가비지값 출력)
- np.arange() : 내장함수 arange와 비슷하지만 배열로 반환
- np.linspace(0, 100, 5) : 0~100을 5등분해서 배열 생성

In [ ]:
arr = np.zeros(5) # 0으로 채워진 배열 생성
print(arr)

print("------------------------------------")

arr = np.zeros(5, dtype="i8")
print(arr)
print(arr.dtype)

print("------------------------------------")

arr = np.zeros(5, dtype="U4")
print(arr)
print(arr.dtype)
arr[0] = 'abc'
arr[1] = 'abcd'
arr[2] = 'abcde'  # 4글자까지로 크기지정 해둬서 입력되지 않음
print(arr)

print("------------------------------------")

arr = np.zeros((2, 3))
print(arr)

[0. 0. 0. 0. 0.]
------------------------------------
[0 0 0 0 0]
int64
------------------------------------
['' '' '' '' '']
<U4
['abc' 'abcd' 'abcd' '' '']
------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.ones((2, 3, 4))
print(arr)

print("------------------------------------")

arr1 = np.zeros((2, 3))
print(arr1)
arr2 = np.ones_like(arr1)   # 0으로 채워진 행렬을 1로 채워줌
print(arr2)

print("------------------------------------")

arr3 = np.empty((4,5))
print(arr3)

print("------------------------------------")

arr4 = np.arange(10)
print(arr4)

print("------------------------------------")

arr5 = np.linspace(0, 100, 5)
print(arr5)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
------------------------------------
[[4.67296746e-307 1.69121096e-306 1.37961302e-306 7.56587585e-307
  1.37961302e-306]
 [1.05699242e-307 8.01097889e-307 2.22522868e-306 1.33511562e-306
  1.24611402e-306]
 [8.34451928e-308 1.24610927e-306 1.24610926e-306 8.34423492e-308
  2.29179042e-312]
 [2.29179042e-312 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]]
------------------------------------
[0 1 2 3 4 5 6 7 8 9]
------------------------------------
[  0.  25.  50.  75. 100.]


# 9. 전치연산(Transpose)

- 행을 열로, 열을 행으로 변경할 때 이용

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.T) # 행과 열을 교환

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# 10. 배열의 크기 변경

- reshape()
- flatten() : 고차원 -> 저차원
- ravel() : 고차원 -> 저차원

In [ ]:
arr = np.arange(12)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [ ]:
arr1 = arr.reshape(3, 4)
print(arr1)
print(arr1.shape)

print("-------------------------------------------")

arr1 = arr.reshape(3, -1)    # 열의 수를 모를 때 "-1"로 채워두면 알아서 나눠짐
print(arr1)

print("-------------------------------------------")

arr1 = arr.reshape(-1, 4)    # 행의 수를 모를 때 "-1"로 채워두면 알아서 나눠짐
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
-------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr2 = arr.reshape(2, 2, 3)  # (면의 개수, 행의 개수, 열의 개수)
print(arr2)

print("-------------------------------------------")

arr2 = arr.reshape(-1, 2, 3)
print(arr2)

print("-------------------------------------------")

arr2 = arr.reshape(2, -1, 3)
print(arr2)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
-------------------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
-------------------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
print(arr1.reshape(12))  # 원소의 개수를 알아야 함
print(arr1.flatten())    # 원소의 개수 몰라도 됨
print(arr1.ravel())

print("-----------------------------------------")

print(arr2.reshape(12))
print(arr2.flatten())
print(arr2.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
-----------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# 11. 배열의 연결(병합)

- hstack(), vstack()
- concatenate()
- dstack(), stack()
- tile()

## 1) hstack(), vstack()

- vstack() : 수직으로 합치기, 개수 다르면 합치기 불가능
- hstack() : 수평으로 합치기

In [ ]:
#### 1차원 배열 ####

a = np.random.randint(0, 10, (4,))  # 범위내 정수를 배열로 출력
print(a)
b = np.ones(4, dtype="i")
print(b)
print("-------------------------------")
print(np.vstack([a, b]))
print("-------------------------------")
print(np.hstack([a, b]))

[7 5 1 4]
[1 1 1 1]
-------------------------------
[[7 5 1 4]
 [1 1 1 1]]
-------------------------------
[7 5 1 4 1 1 1 1]


In [ ]:
#### 2차원 배열 ####

a = np.random.randint(0, 10, (1, 4))
b = np.random.randint(0, 10, (1, 4))
print(a, b)
print("-------------------------------")
print(np.vstack([a, b]))
print("-------------------------------")
print(np.hstack([a, b]))

[[6 6 0 5]] [[1 5 9 5]]
-------------------------------
[[6 6 0 5]
 [1 5 9 5]]
-------------------------------
[[6 6 0 5 1 5 9 5]]


## 2) concatenate()

- 프로그램 짤 때 용이, 합치는 방향 변수 지정 가능

In [ ]:
#### 1차원 ####

a = np.random.randint(0, 10, (4,))  # 범위내 정수를 배열로 출력
print(a)
b = np.ones(4, dtype="i")
print(b)
print("-------------------------------")
print(np.concatenate([a, b]))

[5 9 3 9]
[1 1 1 1]
-------------------------------
[5 9 3 9 1 1 1 1]


In [ ]:
#### 2차원 배열 ####

a = np.random.randint(0, 10, (2, 4))
b = np.random.randint(0, 10, (2, 4))
print(a)
print("-------------------------------")
print(b)
print("-------------------------------")
print(np.concatenate([a, b], axis=0))
print("-------------------------------")
print(np.concatenate([a, b], axis=1))

[[1 6 3 4]
 [3 1 4 2]]
-------------------------------
[[3 4 9 4]
 [0 6 6 9]]
-------------------------------
[[1 6 3 4]
 [3 1 4 2]
 [3 4 9 4]
 [0 6 6 9]]
-------------------------------
[[1 6 3 4 3 4 9 4]
 [3 1 4 2 0 6 6 9]]


In [ ]:
a = np.random.randint(0, 10, (3, 4))
b = np.random.randint(0, 10, (3, 2))
print(a, b)
print("-------------------------------")
# print(np.concatenate([a, b], axis=0)) 사이즈가 달라 불가능
print(np.concatenate([a, b], axis=1))

[[8 0 1 9]
 [0 8 1 5]
 [1 0 2 0]] [[8 6]
 [0 5]
 [0 0]]
-------------------------------
[[8 0 1 9 8 6]
 [0 8 1 5 0 5]
 [1 0 2 0 0 0]]


In [ ]:
#### 3차원 배열 ####

a = np.random.randint(0, 10, (5, 2, 3))
b = np.random.randint(0, 10, (4, 2, 3))
print(a)
print("-------------------------------")
print(b)
print("-------------------------------")
c = np.concatenate([a, b], axis=0)
print(c)
print(c.shape)
# print(np.concatenate([a, b], axis=1))
# print(np.concatenate([a, b], axis=2))

[[[6 6 8]
  [8 0 2]]

 [[3 0 8]
  [6 3 8]]

 [[7 8 0]
  [9 4 7]]

 [[7 2 6]
  [6 5 3]]

 [[4 0 5]
  [9 5 0]]]
-------------------------------
[[[2 2 3]
  [8 3 3]]

 [[0 2 1]
  [8 9 5]]

 [[2 5 0]
  [9 4 6]]

 [[7 1 3]
  [0 6 5]]]
-------------------------------
[[[6 6 8]
  [8 0 2]]

 [[3 0 8]
  [6 3 8]]

 [[7 8 0]
  [9 4 7]]

 [[7 2 6]
  [6 5 3]]

 [[4 0 5]
  [9 5 0]]

 [[2 2 3]
  [8 3 3]]

 [[0 2 1]
  [8 9 5]]

 [[2 5 0]
  [9 4 6]]

 [[7 1 3]
  [0 6 5]]]
(9, 2, 3)


In [ ]:
a = np.random.randint(0, 10, (4, 2, 3))
b = np.random.randint(0, 10, (4, 3, 3))

# print(np.concatenate([a, b], axis=0))
print(np.concatenate([a, b], axis=1))
# print(np.concatenate([a, b], axis=2))

[[[5 1 0]
  [0 1 6]
  [2 7 5]
  [3 4 3]
  [4 7 9]]

 [[5 7 7]
  [6 1 5]
  [2 8 4]
  [4 6 6]
  [8 9 3]]

 [[8 5 9]
  [3 7 9]
  [7 4 6]
  [6 7 0]
  [2 4 6]]

 [[2 5 1]
  [0 2 1]
  [1 4 6]
  [1 6 2]
  [4 9 0]]]


In [ ]:
a = np.random.randint(0, 10, (4, 2, 3))
b = np.random.randint(0, 10, (4, 2, 4))

# print(np.concatenate([a, b], axis=0))
# print(np.concatenate([a, b], axis=1))
print(np.concatenate([a, b], axis=2))
print(np.concatenate([a, b], axis=-1))

[[[3 1 0 7 8 6 4]
  [4 5 9 8 5 9 1]]

 [[3 4 1 5 0 2 6]
  [9 2 3 1 5 7 8]]

 [[2 2 1 5 3 7 2]
  [9 8 2 7 3 6 9]]

 [[3 5 0 0 5 0 7]
  [3 7 6 3 6 8 1]]]
[[[3 1 0 7 8 6 4]
  [4 5 9 8 5 9 1]]

 [[3 4 1 5 0 2 6]
  [9 2 3 1 5 7 8]]

 [[2 2 1 5 3 7 2]
  [9 8 2 7 3 6 9]]

 [[3 5 0 0 5 0 7]
  [3 7 6 3 6 8 1]]]


## 3) stack(), dstack() : 기준이 3차원


- stack() : 차원증가
- dstack() (=np.stack([a1, a2], axis=2)) :  열(깊이)로만 합침

In [ ]:
a1 = np.ones((3, 4))
a2 = np.zeros((3, 4))

a3 = np.stack([a1, a2], axis=0)  # 면으로
print(a3)
print(a3.shape)
print("-------------------------------")
a3 = np.stack([a1, a2], axis=1)  # 행으로
print(a3)
print(a3.shape)
print("-------------------------------")
a3 = np.stack([a1, a2], axis=2)  # 열로
print(a3)
print(a3.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)
-------------------------------
[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]
(3, 2, 4)
-------------------------------
[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]
(3, 4, 2)


In [ ]:
a1 = np.ones((3, 4))
a2 = np.zeros((3, 4))

a3 = np.dstack([a1, a2])
print(a3)
print(a3.shape)

[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]
(3, 4, 2)


In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

a3 = np.dstack([a1, a2])
print(a3)
print(a3.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [ ]:
a = np.random.randint(0, 10, (2, 2, 3))
b = np.random.randint(0, 10, a.shape) # 같은 크기일 경우 사용 가능
c = np.random.randint(0, 10, a.shape)

d = np.dstack([a, b, c])
print(d)
print(d.shape)
print("-----------------------------")
e = np.stack([a, b, c], axis=2)
print(e)
print(e.shape)

[[[3 1 7 2 9 0 9 5 4]
  [8 3 0 7 3 0 8 1 2]]

 [[7 7 4 5 7 2 6 9 6]
  [9 6 9 4 6 5 5 7 4]]]
(2, 2, 9)
-----------------------------
[[[[3 1 7]
   [2 9 0]
   [9 5 4]]

  [[8 3 0]
   [7 3 0]
   [8 1 2]]]


 [[[7 7 4]
   [5 7 2]
   [6 9 6]]

  [[9 6 9]
   [4 6 5]
   [5 7 4]]]]
(2, 2, 3, 3)


## 4) tile()

- ?np.tile
- np.tile(A, reps) : reps를 A만큼 반복

In [ ]:
a = 1
b = np.array([0, 1])
c = np.array([[0, 1], [2, 3]])

In [ ]:
#### reps가 상수일 경우 ####

print(np.tile(a, 3))
print("-----------------------------")
print(np.tile(b, 3))
print("-----------------------------")
print(np.tile(c, 3))

[1 1 1]
-----------------------------
[0 1 0 1 0 1]
-----------------------------
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]]


In [ ]:
#### reps가 튜플일 경우 ####

print(np.tile(a, (2, 3)))
print("-----------------------------")
print(np.tile(b, (2, 3)))
print("-----------------------------")
print(np.tile(c, (2, 3)))

[[1 1 1]
 [1 1 1]]
-----------------------------
[[0 1 0 1 0 1]
 [0 1 0 1 0 1]]
-----------------------------
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [0 1 0 1 0 1]
 [2 3 2 3 2 3]]


# 12. Broadcasting

- http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html#broadcast-visualization
- 규칙
    - 축의 길이가 같으면 가능
    - 배열 중 하나의 길이가 1인 경우 가능

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1])
print(a+b)

print("-----------------------------")

a = np.array([1, 2, 3])
b = np.array([1, 2])
print(a+b)

[2 3 4]
-----------------------------


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

-----

In [ ]:
a = np.vstack([ range(7)[i : i+3] for i in range(5) ])

In [ ]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [ ]:
for i in range(5):
    print(range(7)[i : i+3])
list(range(7)[i : i+3] for i in range(5))

range(0, 3)
range(1, 4)
range(2, 5)
range(3, 6)
range(4, 7)


[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

-----

In [ ]:
x = np.vstack([ range(7)[i : i+3] for i in range(5) ])
y = np.arange(5)[:, np.newaxis] # 차원을 증가 시킬 때 열을 기준으로 축 생성 (=np.arange(5).reshape(5,1))
print(y)
z = np.arange(3).reshape(1,3)   # =reshape(-1,1)
print(z)

print(x+y)
print(x*z)

[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2]]
[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]
[[ 0  1  4]
 [ 0  2  6]
 [ 0  3  8]
 [ 0  4 10]
 [ 0  5 12]]


# 13. 차원 축소(Dimension reduction) 연산

- 최대값/최솟값 : max(), min(), [ argmax(), argmin() ] -> 위치 알려줌
- 대표값 : mean(), sum(), median(), std(), var()
- 논리값 : all(), any()
- ...

In [ ]:
x = np.array([1, 3, 2, -3])

print(np.max(x))
print("max위치 :", np.argmax(x)) # 위치 출력
print("min위치 :", np.argmin(x))

3
max위치 : 1
min위치 : 3


In [ ]:
x = np.array([[1, 3, 2, -3], [5, 20, -2, 1]])

print(np.max(x))
print("max위치 :", np.argmax(x)) # 위치 출력
print("min위치 :", np.argmin(x))

20
max위치 : 5
min위치 : 3


# 14. 기술 통계

- sum(), mean()
- max(), min()
- var(), std()
- len()
- median()
- percentile() -> 사분위수
- ...

-----

    import scipy.stats
    scipy.stats.describe(x) -> 자료의 정보를 한번에 출력

In [ ]:
import scipy.stats

x = np.random.randn(20)
print(x)
print()
print(scipy.stats.describe(x))

[-0.29415684  0.92750121  0.49012972  0.46576487  0.46800119 -0.4966755
 -0.9486472  -2.49079826  1.4815788   0.93583777  0.52020802  1.80807132
  2.04989552  1.56749882  2.12481328 -0.04745627  0.82534551  1.04451983
 -1.02890337  2.7742303 ]

DescribeResult(nobs=20, minmax=(-2.4907982618058404, 2.774230302899723), mean=0.6088379342820246, variance=1.5723170641923365, skewness=-0.5551444245305336, kurtosis=0.20162196842336888)


# 15. 정렬

In [ ]:
arr = np.array([[4, 3, 5, 7],
                [1, 12, 11, 9],
                [2, 15, 1, 14]])

In [ ]:
print(np.sort(arr))          # 행기즌
print("-----------------------------")
print(np.sort(arr, axis=0))  # 열기준

[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
-----------------------------
[[ 1  3  1  7]
 [ 2 12  5  9]
 [ 4 15 11 14]]


In [ ]:
print(arr)

# 원본에 적용
arr = np.sort(arr)
print(arr)

[[ 4  3  5  7]
 [ 1 12 11  9]
 [ 2 15  1 14]]
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]


In [ ]:
arr = np.array([[4, 3, 5, 7],
                [1, 12, 11, 9],
                [2, 15, 1, 14]])

# 또 다른 방법
arr.sort()
print(arr)

[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]


In [ ]:
#### argsort() ####

arr = np.array([42, 38, 12, 25])

idx = np.argsort(arr)
print(arr[idx])

[12 25 38 42]


In [ ]:
#### 내림차순 ####

print(np.sort(arr)[::-1])
print(arr[np.argsort(-arr)])

[42 38 25 12]
[42 38 25 12]


In [ ]:
#### 슬라이싱 : 배열[시작위치 : 끝위치 : 간격]####

ex = np.arange(10)

print(ex[:])
print(ex[::2])
print(ex[::-1])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


# 16. 난수

- rand() : 0~1사이의 균일분포에서 난수 생성
- randn() : 정규분포에서 난수 생성
- randint() : 균일분포에서 정수값으로 난수 생성

In [ ]:
print(np.random.rand(10))
print("------------------------------------------------------------------")
print(np.random.rand(3, 2, 3))

[0.86779102 0.9547079  0.30626128 0.52534568 0.22347331 0.92030606
 0.11007681 0.48014772 0.23643741 0.55800629]
------------------------------------------------------------------
[[[0.13801101 0.09614193 0.18863242]
  [0.65949668 0.97202637 0.09414209]]

 [[0.74297097 0.74893236 0.18025182]
  [0.06196559 0.5987661  0.39793245]]

 [[0.61106884 0.55940973 0.44401546]
  [0.17688577 0.5051913  0.30373232]]]


In [ ]:
print(np.random.randint(10)) # 0~9 사이의 난수 출력
print("-----------------------------------------------------")
print(np.random.randint(11, 20))  # 11~19 사이의 난수 출력
print("-----------------------------------------------------")
print(np.random.randint(11, 20, size=100))  # size로 개수 선택
print("-----------------------------------------------------")
print(np.random.randint(11, 20, size=(2, 5)))

5
-----------------------------------------------------
12
-----------------------------------------------------
[12 16 13 13 19 11 17 18 13 11 12 19 18 14 13 14 17 18 16 15 12 16 12 19
 18 17 15 17 14 16 15 12 17 13 16 15 16 13 11 17 19 18 18 19 17 14 19 17
 16 16 17 14 15 11 18 12 13 14 15 19 13 14 16 14 12 19 11 17 13 18 19 11
 18 17 18 16 19 13 19 11 17 12 12 16 15 17 18 18 13 12 17 15 13 16 17 15
 19 16 16 12]
-----------------------------------------------------
[[17 16 19 16 19]
 [11 12 14 16 17]]


## 1) 재현성(난수 고정)

- np.random.seed(10)

In [ ]:
np.random.seed(5)
np.random.rand(3)

array([0.22199317, 0.87073231, 0.20671916])

## 2) 데이터의 순서 바꾸기

- np.random.shuffle(x)

In [ ]:
x = np.arange(10)
print(x)

np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[1 5 2 9 7 0 3 4 6 8]


## 3) 샘플링 : 복원(default), 비복원

- np.random.choice(x,y) : 복원 / x개의 수 중에서 y번 추출
- np.random.choice(x, y, replace=False) : 비복원
- np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) -> 각 수마다 나올 확률 조정 가능

In [ ]:
print(np.random.choice(5, 10)) # 0~4 5개의 수 중에서 10번 추출

[0 0 4 4 1 3 3 2 4 1]


In [ ]:
print(np.random.choice(7, 5, replace=False))

[2 1 0 5 3]


In [ ]:
print(np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]))  # 각 수마다 나올 확률 조정 가능

[2 2 3 3 3 2 2 2 3 2]


# 17. 정수형 데이터 카운팅

- unique()
- bincount()

## 1) unique()

- 중복 제외한 배열 출력
- np.unique(arr, return_counts=True) : 중복 제외한 배열과 각 원소의 개수 추출

In [ ]:
arr = np.array(['a', 'b', 'b', 'c', 'a'])

In [ ]:
print(len(arr))
print(np.unique(arr), len(np.unique(arr)))

5
['a' 'b' 'c'] 3


In [ ]:
idx, cnt = np.unique(arr, return_counts=True)
print(idx, cnt)

['a' 'b' 'c'] [2 2 1]


## 2) bincount()

- 발생하지 않은 사건에 대해서도 카운팅
- np.bincount(arr, minlength=n) : n의 범위내에서 나오지 않은 수도 카운트해서 출력

In [ ]:
arr = np.array([1, 1, 2, 2, 2, 3])  # 주사위 눈이라 가정(0~5)

print(np.unique(arr, return_counts=True))

print(np.bincount(arr))
print(np.bincount(arr, minlength=6))

(array([1, 2, 3]), array([2, 3, 1], dtype=int64))
[0 2 3 1]
[0 2 3 1 0 0]


# ** 실습예제 P.542 **

- 영화평점 데이터
- https://grouplens.org
    - ml-100k.zip (size: 5 MB, checksum)

---

        np.loadtxt("data\ml-1m\\ratings.dat", delimiter="::", dtype=np.int64) : 파일 불러오기
        np.savetxt("data/ml-1m/ratings_mean.csv", np.array(means), delimiter=",", fmt="%.2f") : 파일 저장하기
        
----

In [ ]:
file = np.loadtxt("data\ml-1m\ratings.dat", delimiter="::", dtype=np.int64)

In [ ]:
print(file)
print(file.shape)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]
(1000209, 4)


In [ ]:
#### 첫행부터 20행까지 출력

print("     {:10}{:10}{:10}{:5}".format("UserID", "MovieID", "Rating", "Timestamp"))
print(file[:20,])

     UserID    MovieID   Rating    Timestamp
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]]


In [ ]:
#### 21행부터 30행까지 userid, movieid만 출력

print("{}{}".format("UserID", "MovieID"))
print(file[21:31, :2])
print(file[21:31, [0, 1]])

UserIDMovieID
[[   1  720]
 [   1 1270]
 [   1  527]
 [   1 2340]
 [   1   48]
 [   1 1097]
 [   1 1721]
 [   1 1545]
 [   1  745]
 [   1 2294]]
[[   1  720]
 [   1 1270]
 [   1  527]
 [   1 2340]
 [   1   48]
 [   1 1097]
 [   1 1721]
 [   1 1545]
 [   1  745]
 [   1 2294]]


In [ ]:
#### 전체 평점에 대한 평균

type(file[:, 2])
file[:, 2].mean()
rat_avg = np.mean(file[:, 2])
print("전체 평점에 대한 평균 :", round(rat_avg, 2))

전체 평점에 대한 평균 : 3.58


In [ ]:
#### 사용자별 평점의 평균 출력(10명만)

User_id = np.unique(file[:,0])

means = []

for id in User_id:
    user = file[file[:, 0] == id, :]
    means.append([id, user[:, 2].mean().round(2)])

print("결과 :", means[:10])

결과 : [[1, 4.19], [2, 3.71], [3, 3.9], [4, 4.19], [5, 3.15], [6, 3.9], [7, 4.32], [8, 3.88], [9, 3.74], [10, 4.11]]


In [ ]:
file[file[:, 0] == 1].mean(axis = 0)[2]

[[id, file[file[:, 0] == id].mean(axis = 0)[2].round(2)] for id in range(1, 11)]

[[1, 4.19],
 [2, 3.71],
 [3, 3.9],
 [4, 4.19],
 [5, 3.15],
 [6, 3.9],
 [7, 4.32],
 [8, 3.88],
 [9, 3.74],
 [10, 4.11]]

In [ ]:
# 결과값을 넘파이를 이용하여 파일로 저장하기

np.savetxt("data/ml-1m/ratings_mean.csv", np.array(means), delimiter=",", fmt="%.2f")